# Generated by Django 2.1.5 on 2019-01-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='swiss_point',
            field=models.IntegerField(default=0),
        ),
    ]
